### ISSUE TITLE
Content-Type header for Prometheus 3.0.0

### ISSUE THREAD

**Issue by jcpunk** [prometheus-community/systemd_exporter#153]
### Is your feature request related to a problem? Please describe.

Prometheus 3.0.0 has the option (by default) to be far more strict about what content it scrapes. This can cause unexpected scrape failures for the prometheus exporter.

### Describe the solution you'd like

Set the header "to the correct value". 

### Describe alternatives you've considered

If a scrape target is not providing the correct Content-Type header the fallback protocol can be specified using the fallback_scrape_protocol parameter. 

### Additional context

From : https://prometheus.io/docs/prometheus/3.0/migration/
> Prometheus v3 is more strict concerning the Content-Type header received when scraping. Prometheus v2 would default to the standard Prometheus text protocol if the target being scraped did not specify a Content-Type header or if the header was unparsable or unrecognised. This could lead to incorrect data being parsed in the scrape. Prometheus v3 will now fail the scrape in such cases.

**Comment by egmc** [comment]
Hi @jcpunk 
I think this exporter already returns correct value for Content-Type as PrometheusText0.0.4 since the exporter uses promhttp internally.

In my environment with version 0.6.0 returns Content-Type as text/plain with version0.0.4.
I have confirmed Prometheus 3.0.0. can scrape it without fallback setting as well.

Have you encountered any actual problems?

```
$ curl -v -s  http://localhost:9558/metrics
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9558 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:9558
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain; version=0.0.4; charset=utf-8
< Date: Fri, 06 Dec 2024 02:45:09 GMT
< Transfer-Encoding: chunked
```

**Comment by jcpunk** [comment]
Looks like is was testing the wrong exporter.  Sorry for the noise.
