### ISSUE TITLE
Error reading CPU stats if the system is running in unified mode

### ISSUE THREAD

**Issue by pelov** [prometheus-community/systemd_exporter#34]
I am running a system using cgroups v2 unified hierarchy using the kernel boot param `systemd.unified_cgroup_hierarchy`. When trying to read the cpu usage metrics systemd exporter returns the following error:

`msg="couldn't get unit's metrics: failed to read CPU usage from control group: unable to read file /sys/fs/cgroup/system.slice/apache2.service/cpuacct.usage_all: open /sys/fs/cgroup/system.slice/apache2.service/cpuacct.usage_all: no such file or directory" source="systemd.go:336"
`

In the unified mode there is no cpuacct controller and no `cpuacct.usage_all file`. Instead the cpu statistics are read from the cpu controller and the cpu.stat file:
```
$ cat /sys/fs/cgroup/system.slice/apache2.service/cpu.stat 

usage_usec 26314432
user_usec 23039841
system_usec 3274591
```

By the way the `cpu.stat` file is also available if the system is running in hybrid mode but under the `/sys/fs/cgroup/unified` directory where the new cgroups v2 hierarchy is mounted.  So, potentially the cpu stats could always be read from this file, you just need to figure out where it is located, i.e. are you running in a hybrid or unified mode.

**Comment by pelov** [comment]
I looked at the code and there is a detection of the cgroups version and the compatibility mode. However, we still need to find out where the cgroup2 hierarchy is mounted.

I can try to fix the code but I need to know should I keep the existing support for cpuacct controller or move entirely to cgroups2?

BTW, one more advantage of using cgroups2 cpu controller is that cpu.stat is available even if CPUAccounting is not on for the given unit.

**Comment by lukasmrtvy** [comment]
@pelov any progress on this? thanks

**Comment by pelov** [comment]
> @pelov any progress on this? thanks
> 

I have a fix on my fork of the project https://github.com/pelov/systemd_exporter since two years. It was based on version 0.4.0 and I just rebased it on the latest 0.5.0 release. It works in both unified and hybrid modes and reads cpu usage from the `cpu` instead of the `cpuacct` controller. Looks like the right solution to me although I don't consider myself a cgroups expert. That's why I am not sending a PR towards the main project.

> See this for detecting cgroup version: https://kubernetes.io/docs/concepts/architecture/cgroups/#check-cgroup-version

The systemd_exporter already contains a code for detecting the cgroup mode.

**Comment by tnn2** [comment]
I tried your patch against main as of today on Rocky Linux 9.1 and it solved the issue there, but it caused a regression and broke[1] systemd_exporter on our Rocky Linux 8.7 fleet so something is wrong with the detection code and it should not be merged as-is.

```
[1]
open /sys/fs/cgroup/cpu/system.slice/prod-backend.service/cpu.stat: no such file or directory
```

**Comment by pelov** [comment]
> I tried your patch against main as of today on Rocky Linux 9.1 and it solved the issue there, but it caused a regression and broke[1] systemd_exporter on our Rocky Linux 8.7 fleet so something is wrong with the detection code and it should not be merged as-is.
> 
> ```
> open /sys/fs/cgroup/cpu/system.slice/prod-backend.service/cpu.stat: no such file or directory
> ```

Looks like I have removed the check for the CPUAccounting property before reading the unit's cpu usage. I suppose on your Rocky Linux 8.7 cpu statistics is not available so the upstream version of systemd_exporter should not return the metric `systemd_unit_cpu_seconds_total` at all.

I made a fix on my branch https://github.com/pelov/systemd_exporter/tree/cpu_stat to restore this check as it is in the upstream version. So, now it should work on the Rocky Linux 8.7. I also compiled a new binary release on my repo https://github.com/pelov/systemd_exporter/releases.

**Comment by jangrewe** [comment]
What's the current recommendation to get this fixed? After a kernel update (i think that triggered it), my container logs are now being flooded with errors regarding the missing `cpuacct.usage_all` files. 
26 Gigs in a less than a day 🙄

PS: Debian bullseye, running the `prometheuscommunity/systemd-exporter:latest` Docker image

**Comment by SuperQ** [comment]
We have removed cgroup metrics from this exporter in favor of recommending cAdvisor.

**Comment by jangrewe** [comment]
Thanks! Could you please update the docs, or note somewhere, that `--path.procfs` isn't supported anymore, and how to replace it?

Besides that, my log is now being flooded with messages like this for every unit: 
```
Oct 30 11:15:12 hades docker[3961165]: ts=2023-10-30T10:15:12.183Z caller=systemd.go:300 level=warn unit=postgresql@13-main.service msg="couldn't get unit's metrics: %s" err="couldn't get unit's InactiveEnterTimestamp property: The maximum number of pending replies per connection has been reached"
```
