### ISSUE TITLE
Feature: systemd-resolve --statistics

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/systemd_exporter#37]
It would be useful to expose systemd-resolve metrics via dbus.

See protocol options: https://www.freedesktop.org/wiki/Software/systemd/resolved/

**Comment by egmc** [comment]
Hi,
I wrote an individual exporter for systemd-resolved recently.
It collects metrics from cli tool output or dbus directly.

https://github.com/egmc/systemd_resolved_exporter

I'm thinking of making a PR for this issue, but I'm not sure about the current status of the project.
Could you tell me some ideas?

**Comment by jpds** [comment]
@egmc Feel free to put in a PR - I'd be keen to have these metrics as well.

**Comment by egmc** [comment]
@jpds 
Thanks, I have just sent a PR for this feature!
