### ISSUE TITLE
Nrefused, send no warning if systemd <239

### ISSUE THREAD

**Issue by juju4** [prometheus-community/systemd_exporter#45]
When installing systemd_exporter on Ubuntu 18.04, there is a spam of logs related to
https://github.com/povilasv/systemd_exporter/blob/master/systemd/systemd.go#L644
installation done with https://github.com/cloudalchemy/ansible-systemd-exporter

I think that systemd version should be tested once and if below, don't issue warning as expected.
Or have a config option to silence message.

Thanks

**Comment by jpds** [comment]
That Ubuntu version is now end-of-life, and you didn't include the error.

A bunch of (cgroup) error messages were removed as part of the v0.6.0 release - so you should retest if this is still the case with that.

**Comment by SuperQ** [comment]
I think we can close this.
