### ISSUE TITLE
Migrate to prometheus-community?

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/systemd_exporter#47]
Hey, if there's interest, we could move this project to the prometheus-community org. @povilasv and any other contributiors can stay as owners. But it would allow for easier updates and publishing to the official community org.

I'm happy to sponsor and support moving this. I would like to see this exporter finally take the full place of the systemd support in the node_exporter so I can deprecate and remove that collector.

**Comment by povilasv** [comment]
Hey,

I would be gladly to move it prometheus-community :)

I've kinda stopped working on this project, as I don't really use it anymore :/

If there are people who would like to join and help maintain this, would be amazing! 

I didn't do this earlier as I thought this project doesn't really get a lot of activity/contributions and I'm not sure whether Prometheus community would take that kind of project :)

**Comment by inglor** [comment]
I think if node_exporter's plans are still to deprecate the systemd support then yes it makes sense to move this to something more official.

**Comment by SuperQ** [comment]
I've created a tracking issue in the Prometheus Community org.

**Comment by povilasv** [comment]
Here we go https://github.com/prometheus-community/systemd_exporter :)

**Comment by povilasv** [comment]
I think I lost access maintainer access now, @SuperQ when you have time add me in :rocket:

**Comment by SuperQ** [comment]
Yup, I fixed up the team access, you should have access again.
