### ISSUE TITLE
User instances of systemd

### ISSUE THREAD

**Issue by DaAwesomeP** [prometheus-community/systemd_exporter#73]
Hello,

Is there a way to monitor a user's systemd instance? These are services run with `systemctl --user` from a user's local session. The exporter could run as this user.

Thanks!

**Comment by qcasey** [comment]
I was also looking for this, seems so:

https://github.com/prometheus-community/systemd_exporter/issues/39#issuecomment-752792529

**Comment by DaAwesomeP** [comment]
That is probably it! Thank you! I may open a pull to add to the README.
