### ISSUE TITLE
Integer overflow when getting memory usage of a service

### ISSUE THREAD

**Issue by amandasaurus** [prometheus-community/systemd_exporter#83]
I have a systemd service which is using 155GiB of RAM. (Yes, that's a lot. Yes, it's supposed to use that much). However v0.5.0 of this exporter did not include the memory usage of this service, but did for other services.

Logging output shows this:

```
Apr 05 15:49:17 routing-osrm1 prometheus_systemd_exporter[968176]: ts=2023-04-05T13:49:17.196Z caller=systemd.go:351 level=warn unit=osrm-car.service msg="couldn't get unit's metrics: %s" err="unsigned integer overflow on token 259327102976"
```

Looks like the wrong type of integers are being used to parse?

**Comment by dswarbrick** [comment]
I have a feeling that this was probably removed by #68.
